using System;

namespace RealEstate.Domain.Entities;

public class Agency { public int Id { get; set; } public string Name { get; set; } = string.Empty; public string Address { get; set; } = string.Empty; public string Phone { get; set; } = string.Empty; public string Logo { get; set; } = string.Empty; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public class Agent { public int Id { get; set; } public int UserId { get; set; } public int? AgencyId { get; set; } public string Emri { get; set; } = string.Empty; public string Mbiemri { get; set; } = string.Empty; public string Telefoni { get; set; } = string.Empty; public string Email { get; set; } = string.Empty; public string Kompania { get; set; } = string.Empty; public string Licenca { get; set; } = string.Empty; }
public class Client { public int Id { get; set; } public int UserId { get; set; } public string Emri { get; set; } = string.Empty; public string Mbiemri { get; set; } = string.Empty; public string Telefoni { get; set; } = string.Empty; public string Email { get; set; } = string.Empty; public decimal Buxheti { get; set; } }
public class PropertyType { public int Id { get; set; } public string Emertimi { get; set; } = string.Empty; public string Pershkrimi { get; set; } = string.Empty; }
public class Property { public int Id { get; set; } public string Titulli { get; set; } = string.Empty; public string Pershkrimi { get; set; } = string.Empty; public int PropertyTypeId { get; set; } public decimal Cmimi { get; set; } public decimal Siperfaqja { get; set; } public int Dhomat { get; set; } public int Banjot { get; set; } public string Adresa { get; set; } = string.Empty; public string Qyteti { get; set; } = string.Empty; public string Statusi { get; set; } = string.Empty; public int AgentId { get; set; } }
public class PropertyImage { public int Id { get; set; } public int PropertyId { get; set; } public string RrugaImazhit { get; set; } = string.Empty; public bool EshteKryesore { get; set; } }
public class PropertyFeature { public int Id { get; set; } public int PropertyId { get; set; } public string Vecoria { get; set; } = string.Empty; }
public class Inquiry { public int Id { get; set; } public int PropertyId { get; set; } public int ClientId { get; set; } public string Mesazhi { get; set; } = string.Empty; public DateTime Data { get; set; } = DateTime.UtcNow; public string Statusi { get; set; } = string.Empty; }
public class Favorite { public int Id { get; set; } public int ClientId { get; set; } public int PropertyId { get; set; } public DateTime Data { get; set; } = DateTime.UtcNow; }
public class Appointment { public int Id { get; set; } public int PropertyId { get; set; } public int ClientId { get; set; } public int AgentId { get; set; } public DateTime Data { get; set; } public string Ora { get; set; } = string.Empty; public string Statusi { get; set; } = string.Empty; }
public class Contract { public int Id { get; set; } public int PropertyId { get; set; } public int ClientId { get; set; } public int AgentId { get; set; } public string Lloji { get; set; } = string.Empty; public decimal Cmimi { get; set; } public DateTime DataFillimit { get; set; } public DateTime? DataPerfundimit { get; set; } public string Statusi { get; set; } = string.Empty; }
public class Message { public int Id { get; set; } public int SenderId { get; set; } public int ReceiverId { get; set; } public string Content { get; set; } = string.Empty; public bool IsRead { get; set; } public DateTime SentAt { get; set; } = DateTime.UtcNow; }
public class Payment { public int Id { get; set; } public int ContractId { get; set; } public decimal Shuma { get; set; } public string LlojiPageses { get; set; } = string.Empty; public DateTime Data { get; set; } = DateTime.UtcNow; public string Statusi { get; set; } = string.Empty; }
public class PropertyReview { public int Id { get; set; } public int PropertyId { get; set; } public int ClientId { get; set; } public int Rating { get; set; } public string Comment { get; set; } = string.Empty; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
